name: Run Shell Commands
on: [push, fork]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "This is out first github action workflow file"